name: Test egi2mne

# Déclenchement automatique à chaque push ou pull request sur la branche main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Téléchargement de ton dépôt sur la machine virtuelle
    - name: Checkout du code
      uses: actions/checkout@v4

    # 2. Configuration de Python 3.10
    - name: Configuration de Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Installation des dépendances (MNE et Numpy)
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install mne numpy

    # 4. Exécution du script de test
    # Note : test_app.py est à la racine, et il ira chercher main.py dans egi2mne/
    - name: Exécution du test de l'application
      run: python test_app.py